#------------------------------------------------------------------------------
# General
#------------------------------------------------------------------------------
name: علیرضاک
description: "یک کتابدار که به دنیای کامپیوتر علاقمند است و از علایقش در مورد لینوکس و اینترنت و دنیای نرم‌افزارهای آزاد می‌نویسد"
url: http://localhost:4000
baseurl: 'blog'

#------------------------------------------------------------------------------
# Markdown processor and code highlighting
#------------------------------------------------------------------------------
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#------------------------------------------------------------------------------
# Pagination and friendly URLs
#------------------------------------------------------------------------------
paginate: 8
paginate_path: /page-:num
permalink: /:title

#------------------------------------------------------------------------------
# Social sharing, comments and RSS.
#------------------------------------------------------------------------------

enable-share: true
# Social share and comments.
disqus-id: 
twitter: alirezayof
github: alireza12186
google: +

rss-feed-limit: 10
rss-show-full: false

#------------------------------------------------------------------------------
# Configuration, plugins, gems, etc..
#------------------------------------------------------------------------------
source: .
destination: ./blog/_site
gems: ['jekyll-paginate']

sass:
    style: :compressed
    sass_dir: assets/css/

